"""Core API for safe waveform-generator identification."""

from wavegen_tool_core.backends import (
    PYVISA_PY_BACKEND,
    SYSTEM_BACKEND,
    VisaBackend,
    normalize_backend,
    validate_backend_transport,
)
from wavegen_tool_core.errors import (
    IdnQueryError,
    MalformedIdnError,
    ResourceDiscoveryError,
    ResourceManagerError,
    ResourceOpenError,
    UnsupportedBackendError,
    UnsupportedConnectionScopeError,
    UnsupportedInstrumentError,
    UnsupportedTransportError,
    VisaCleanupError,
    WavegenError,
)
from wavegen_tool_core.identity import (
    CANONICAL_MANUFACTURER,
    CANONICAL_MODEL,
    CANONICAL_MODEL_ID,
    InstrumentIdentity,
    RECOGNIZED_MANUFACTURERS,
    parse_idn,
    resolve_supported_identity,
)
from wavegen_tool_core.transport import classify_transport, detect_resource_transport
from wavegen_tool_core.visa import (
    DEFAULT_TIMEOUT_MS,
    LIVE_VERIFY_TIMEOUT_MS,
    SERIAL_TERMINATIONS,
    IdentificationResult,
    ResourceListEntry,
    ResourceListResult,
    identify_instrument,
    list_resources,
    normalize_serial_baud_rate,
    normalize_serial_termination,
)

__all__ = [
    "CANONICAL_MANUFACTURER",
    "CANONICAL_MODEL",
    "CANONICAL_MODEL_ID",
    "DEFAULT_TIMEOUT_MS",
    "LIVE_VERIFY_TIMEOUT_MS",
    "PYVISA_PY_BACKEND",
    "SYSTEM_BACKEND",
    "IdentificationResult",
    "IdnQueryError",
    "InstrumentIdentity",
    "MalformedIdnError",
    "ResourceDiscoveryError",
    "RECOGNIZED_MANUFACTURERS",
    "ResourceListEntry",
    "ResourceListResult",
    "ResourceManagerError",
    "ResourceOpenError",
    "SERIAL_TERMINATIONS",
    "UnsupportedBackendError",
    "UnsupportedConnectionScopeError",
    "UnsupportedInstrumentError",
    "UnsupportedTransportError",
    "VisaBackend",
    "VisaCleanupError",
    "WavegenError",
    "classify_transport",
    "detect_resource_transport",
    "identify_instrument",
    "list_resources",
    "normalize_backend",
    "normalize_serial_baud_rate",
    "normalize_serial_termination",
    "parse_idn",
    "resolve_supported_identity",
    "validate_backend_transport",
]
